
<style>
table 
{  
  font-family: Arial, sans-serif;  
  border-collapse: collapse;  
  width: 100%;  
  margin-top: 30px;
}
td, th 
{  
  border: 1px solid #dddddd;  
  text-align: left;  
  padding: 8px;  
}
tr:nth-child(even) 
{ 
  background-color: #dddddd; 
}
.point-id
{
  width:5%;
} 
.point-name
{
  width:30%;
}

</style>

<h2>Points of Sale list</h2>

<table>
  <tr>
    <th class="point-id">ID</th>
    <th class="point-name">Name</th>
    <th>Address</th>
    <th>Is Available</th>
  </tr>
    <?php
        foreach ($block->getPointCollection() as $key=>$point)
        {
            echo '<tr>
                  <td>'.$point->getPointId().'</td>
                  <td>'.$point->getName().'</td>
                  <td>'.$point->getAddress().'</td>';
                  if($point->getIsAvailable() == 1) echo '<td>YES</td>';
                  elseif($point->getIsAvailable() == 0) echo '<td>NO</td>';
                  else echo '<td>not set</td>';
            echo '</tr>';
        }
    ?>    
</table>

</body>
</html>
